on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run:
          sudo apt-get install -y libbz2-dev
      - uses: actions/setup-go@main
        with:
          go-version-file: 'go.mod'
      - run:
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          verbose: true